apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: christianh814/gobg
  newTag: "yellow"

patches:
  - target:
      version: v1
      kind: Service
      name: gobg
    patch: |
      - op: add
        path: /spec/type
        value: NodePort
      - op: add
        path: /spec/ports/0/nodePort
        value: 30182
