apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gobg
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - environment: dev
      - environment: stage
      - environment: prod
  template:      
    metadata:
      name: 'gobg-{{.environment}}'
    spec:
      project: default
      sources:
        - repoURL: https://github.com/<repo>
          targetRevision: main
          path: 'kustomize/env/overlays/{{.environment}}'
      destination:
        name: in-cluster
        namespace: 'gobg-{{.environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
