---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gobg-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/wouary/argocd-applications
    targetRevision: main
    path: kustomize/env/overlays/dev/
  destination:
    namespace: gobg-dev
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 3m0s
        factor: 2
