apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: endor
  namespace: argocd
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  sourceRepos:
  - '*'
  destinationServiceAccounts:
    - server: https://kubernetes.default.svc
      namespace: kuard
      defaultServiceAccount: kuard-deployer
