apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kuard-deployer-role
  namespace: kuard
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
