apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kuard-deployer-binding
  namespace: kuard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kuard-deployer-role
subjects:
- kind: ServiceAccount
  name: kuard-deployer
  namespace: kuard
