apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-go
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - environment: dev
      - environment: stage
      - environment: prod
  template:      
    metadata:
      name: 'simple-go-{{.environment}}'
    spec:
      project: default
      sources:
        - repoURL: https://akuity.github.io/demo-helm-charts
          chart: simple-go
          targetRevision: 0.2.1
          helm:
            valueFiles:
            - $values/helm/values/common/values.yaml
            - $values/helm/values/env/{{.environment}}/values.yaml  
        - repoURL: https://github.com/<repo>
          targetRevision: main
          ref: values
      destination:
        name: in-cluster
        namespace: 'sg-{{.environment}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
